### ISSUE TITLE
Image not support

### ISSUE THREAD

**Issue by LiYanan2004** [gonzalezreal/swift-markdown-ui#184]
Image doesn't appear in the final view. Will it be available in the future?

**Comment by LiYanan2004** [comment]
<img width="633" alt="截屏2023-01-27 23 04 20" src="https://user-images.githubusercontent.com/37542129/215118543-51842283-98f0-40f7-9f60-5fecbc4cf6ba.png">

More specifically, network image the example above

**Comment by gonzalezreal** [comment]
Hi @LiYanan2004,

MarkdownUI can render images, you can see it for yourself in the [companion demo project](https://github.com/gonzalezreal/swift-markdown-ui/blob/main/Examples/Demo).

If there is a specific issue with images, please open an issue using the provided **Bug report** template and filling the required information (in your case, the markdown text to reproduce it) so that I can take a look. In the meantime I will close this one.
