### ISSUE TITLE
Conflict with swift-markdown

### ISSUE THREAD

**Issue by Mx-Iris** [gonzalezreal/swift-markdown-ui#206]
<img width="1122" alt="iShot_2023-03-29_01 04 02" src="https://user-images.githubusercontent.com/61279231/228315027-5d870017-2003-4451-a546-6be508dffea0.png">

What should I do if I want to use both packages for my project ?

**Comment by gonzalezreal** [comment]
This is a known issue. Both packages use the `cmark-gfm` library to parse Markdown. A possible solution would be to adopt `swift-markdown` to parse the Markdown content instead of using `cmark-gfm` directly. Unfortunately, `swift-markdown` doesn't follow a semantic versioning strategy like `swift-markdown-ui`. We would need to depend on the `main` branch to use it, which would disable semantic versioning in `swift-markdown-ui` (package resolution fails if you require a package version that depends on an unversioned package).
