### ISSUE TITLE
Image was clipped and stretched with specific markdown text

### ISSUE THREAD

**Issue by PandaZhang530** [gonzalezreal/swift-markdown-ui#269]
here is the markdown text :

`" Raising the Funds Traditionally\n![](https://academy-public.coinmarketcap.com/optimized-uploads/ac90526718d74b908ac2a967af50339d.png)aa "`
        

here is the screen shot of clipping and stretching:

<img width="472" alt="image" src="https://github.com/gonzalezreal/swift-markdown-ui/assets/140152146/12d634c3-aff4-43ad-a4c9-e2b4f18dd8cf">

**Comment by gonzalezreal** [comment]
Hi @PandaZhang530,

I think the problem is the `aa` text at the end. This causes the image to be laid out next to the text and treated as an inline image, which works differently with images in separate paragraphs. Notice that inline images cannot be styled and are rendered at the original size.

There are a couple of ways to fix this:

1. Make the image smaller so it can be laid out in line with the text.
2. Place the image in a different paragraph and remove the `aa` text.

```
Raising the Funds Traditionally

![](https://academy-public.coinmarketcap.com/optimized-uploads/ac90526718d74b908ac2a967af50339d.png)
```
![Simulator Screenshot - iPhone 14 - 2023-10-16 at 08 25 22](https://github.com/gonzalezreal/swift-markdown-ui/assets/373190/3056e7c9-85d5-48b8-b5ea-29ed7055bc37)

**Comment by PandaZhang530** [comment]
> Hi @PandaZhang530,
> 
> I think the problem is the `aa` text at the end. This causes the image to be laid out next to the text and treated as an inline image, which works differently with images in separate paragraphs. Notice that inline images cannot be styled and are rendered at the original size.
> 
> There are a couple of ways to fix this:
> 
> 1. Make the image smaller so it can be laid out in line with the text.
> 2. Place the image in a different paragraph and remove the `aa` text.
> 
> ```
> Raising the Funds Traditionally
> 
> ![](https://academy-public.coinmarketcap.com/optimized-uploads/ac90526718d74b908ac2a967af50339d.png)
> ```
> 
> ![Simulator Screenshot - iPhone 14 - 2023-10-16 at 08 25 22](https://user-images.githubusercontent.com/373190/275410324-3056e7c9-85d5-48b8-b5ea-29ed7055bc37.png)

Yes, you are right . I will fix this by adding two line breaks after each markdown image
