### ISSUE TITLE
Crash on placeSubviews

### ISSUE THREAD

**Issue by OmarJalil** [gonzalezreal/swift-markdown-ui#289]
Thank you for contributing to MarkdownUI!

Before you submit an issue, please complete the report with all the relevant details for your bug and go through every item in the checklist.

**Describe the bug**
FlowLayout > placeSubviews > line 24 is crashing
> Thread 1: Fatal error: view origin is invalid: (nan, 8.0), UnitPoint(x: 0.0, y: 0.0), (0.0, 0.0)

**Checklist**
- [x] I can reproduce this issue with a vanilla SwiftUI project.
- [x] I can reproduce this issue using the `main` branch of this package.
- [x] This bug hasn't been addressed in an [existing GitHub issue](https://github.com/gonzalezreal/swift-markdown-ui/issues).

**Steps to reproduce**
I use this Markdown in a list of text, the user sends. This text is crashing
```
Markdown(MarkdownContent("Words: words words word \n----\n---\n\\\n\\\n![](https://i1.wp.com/vaventura.com/wp-content/uploads/2018/04/archeVA.jpg?resize=1600%2C1774&ssl=1)"))
```  

**Expected behavior**
It shouldn't crash

**Screenshots**
<img width="1177" alt="Screenshot 2024-01-04 at 4 04 59 p m" src="https://github.com/gonzalezreal/swift-markdown-ui/assets/25520015/580fd873-d840-4a41-ad94-a977205bbe8b">

**Version information**
- MarkdownUI: main
- OS: iOS 17.2
- Xcode: 15.1.0

**Additional context**

**Comment by gonzalezreal** [comment]
I could not reproduce the crash with the information you provided. MarkdownUI is rendering the content in the issue description just as expected.

![Simulator Screen Shot - iPhone 14 Pro - 2024-01-06 at 11 05 56](https://github.com/gonzalezreal/swift-markdown-ui/assets/373190/b4417e8e-bf95-46f1-a23e-2daf3238d6b6)

Given that the crash cause is the invalid coordinates provided by the system in [`placeSubviews(in:proposal:subviews:cache:)`](https://developer.apple.com/documentation/swiftui/layout/placesubviews(in:proposal:subviews:cache:)), the root cause must lay in the view hierarchy particular to your app. 

I can only help if you provide a project reproducing the crash in isolation.
