### ISSUE TITLE
Make cmark-gfm as dependency package

### ISSUE THREAD

**Issue by nbmisen** [gonzalezreal/swift-markdown-ui#306]
My project uses github.com/apple/swift-markdown's SPM as a dependency, and swift-markdown uses https://github.com/apple/swift-cmark as a dependency. When I also use swift-markdown-ui as a dependency, Xcode indicates a conflict with cmark-gfm. Therefore, is it possible to use cmark-gfm as a dependency rather than as source in the code?

Conflict report：multiple targets named 'cmark-gfm' in: 'swift-cmark', 'swift-markdown-ui'

**Comment by andreivladmatei** [comment]
I have the same issue. What's the recommendation?

**Comment by zhang-hongshen** [comment]
Same issue. Is this repository still active ?

**Comment by gonzalezreal** [comment]
Hey folks,
Sorry for the late response. Unfortunately, [apple/swift-cmark](https://github.com/apple/swift-cmark) is not using semantic versioning, so is not possible make a flexible version requirement.

For instance, this doesn't work:

```swift
dependencies: [
  .package(url: "https://github.com/apple/swift-cmark", "swift-4.2-RELEASE"..<"swift-5.10-RELEASE")
]
```

Additionally, [apple/swift-markdown](https://github.com/apple/swift-markdown) depends on the `gfm` branch, instead of an specific version:

https://github.com/apple/swift-markdown/blob/907674c2ae2d24c32fba50101821b1a7fdd291e2/Package.swift#L48

I will be happy to use apple/swift-cmark if it where possible to have a flexible requirement on the version. I am open to any ideas.

Thanks!

**Comment by lovetodream** [comment]
Hey everyone, I had the same issue a few months ago and created a fork which uses [apple/swift-markdown](https://github.com/apple/swift-markdown). Initially I've planned to open a PR here but since I had limited time and needed to remove [a few methods](https://github.com/lovetodream/swift-markdown-ui/commit/88465c9ec3a53d17a971654db2b172a3582447c7#diff-c17f4bb1fc57711e2d8f720258ae448f4f6a0818adb54dd573baef5d6b092478) from the public API (might be due to lack of knowledge), I've restrained from doing so. 
Maybe it is of some help to anyone.
If this is interesting to you @gonzalezreal, I can open a PR.
Here's the branch: https://github.com/lovetodream/swift-markdown-ui/tree/feature/swift-markdown-refactor

**Comment by BelDaw** [comment]
Having the same issue. Has there been a solution for this yet?

**Comment by hyperlink** [comment]
> Having the same issue. Has there been a solution for this yet?

I ended up using @lovetodream branch which WFM.

**Comment by wesleymccloy** [comment]
@gonzalezreal [swiftlang/swift-cmark](https://github.com/swiftlang/swift-cmark) has added semver tags ([0.5.0](https://github.com/swiftlang/swift-cmark/releases/tag/0.5.0) for example)

**Comment by gonzalezreal** [comment]
@wesleymccloy Good to know! I will give it a try.

**Comment by gonzalezreal** [comment]
You can try it here:
- https://github.com/gonzalezreal/swift-markdown-ui/pull/348

I would like to have some feedback before merging that PR. Please react with thumbs up if it works for you. Otherwise, let me know in the comments.

**Comment by hyperlink** [comment]
Hi @gonzalezreal  I have noticed this warning in Xcode otherwise no issues:

<img width="683" alt="image" src="https://github.com/user-attachments/assets/10bae5ce-8ab3-4364-9979-154d400eabd3">

**Comment by hyperlink** [comment]
I created a new project and added swiftlang’s swift-markdown. However, I’m still seeing the warning.

<img width="1758" alt="image" src="https://github.com/user-attachments/assets/00e4b5c2-11d8-4aaf-a9c9-c618f40461eb">

The warning should be gone in the main branch, but the 0.5.0 tag still references Apple’s swift-markdown.

https://github.com/swiftlang/swift-markdown/blob/8f79cb175981458a0a27e76cb42fee8e17b1a993/Package.swift#L49

**Comment by gonzalezreal** [comment]
Yep, that could be the issue. So, the workaround is to use the main branch for `swiftlang/swift-markdown` until there is a new tag that uses the proper organization name for `swift-cmark`. There is nothing we can do on our side.

**Comment by gonzalezreal** [comment]
I don't see any reason to hold #348, so I am going to merge it.
